# Site settings
title: Dima Afonin's Blog
email: shouldgo@me.com
description: >- # this means to ignore newlines until "baseurl:"
  Photography, travel, and travel photography.
domain: shouldgo.me
baseurl: ""
url: https://shouldgo.me
permalink: /blog/:title/
twitter_username: shouldgo
github_username:  shouldgo
google_analytics: G-2C1KSKG809

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
  - jekyll-paginate-v2 # https://github.com/sverrirs/jekyll-paginate-v2
  - jekyll-loading-lazy # https://github.com/gildesmarais/jekyll-loading-lazy 
  - jekyll-multiple-languages-plugin # https://github.com/kurtsson/jekyll-multiple-languages-plugin
  - jekyll-target-blank #https://github.com/keithmifsud/jekyll-target-blank

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed

# Localization settings
languages: ["en", "ru"]
exclude_from_localizations: ["javascript", "images", "css", "assets"]
default_locale_in_subfolder: false

# Excerpt settings
show_excerpts: false # We're using our own excerpt display in the post cards
excerpt_separator: <!--more--> # Optional custom excerpt separator

# Pagination settings
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 0 # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  permalink: '/page:num/'
  # title: ':title - page :num' # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  # tag: '' # Optional, the default tag to use, omit to disable
  # locale: '' # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts
  trail: # Controls how the pagination trail for the paginated pages look like. Optional,omit or set both before and after to zero to disable. 
    before: 2
    after: 2
  extension: html # Optional, the default file extension for generated pages (e.g html, json, xml).
  indexpage: 'index' # Optional, the default name of the index file for generated pages (e.g. 'index.html')

# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - "*.zsh"