#-------------------------------
# Site Settings
title: shouldgo.me
logo: # You can add own logo. For example '/images/logo.png'.
description: Блог Димы Афонина с фотографиями, путешествиями и фотографиями из путешествий.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'блог'
      url: '/blog/'
    - title: 'обо мне'
      url: '/about/'
    - title: 'контакты'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  enable: false
  hero__title: 
  hero__description:
  hero__image: # You can add hero image. For example '/images/06.jpg'


#-------------------------------
# Author Global Settings
author:
  author__name: Dima Afonin
  author__bio: 
  author__avatar:


#-------------------------------
# Blog Section Settings
blog__settings:
  enable: true
  blog__title:
  blog__description:


#-------------------------------
# Videos Section Settings
videos__settings:
  enable: false
  videos__title:
  videos__description:


#-------------------------------
# Tag Section Settings
tag__settings:
  enable: false
  tag: travel # To display the tag section, specify your favorite tag.


#-------------------------------
# Author Section Settings
author__section:
  enable: false
  author__section__title:
  author__section__description:
  aurhor__section__button__text:
  aurhor__section__button__link: /about
  author__section__big__image:
  author__section__small__image:


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  enable: false
  mailchimp__title:
  mailchimp__description:
  mailchimp__identifier: # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text:
  mailchimp__button__text:
  mailchimp__background__image:


#-------------------------------
# Footer Settings
footer__description: Блог Димы Афонина с фотографиями, путешествиями и фотографиями из путешествий.


# Social Links
social:
- {icon: "facebook", link: "https://facebook.com/dima.afonin"}
- {icon: "instagram", link: "http://instagram.com/shouldgo/"}
- {icon: "linkedin", link: "https://linkedin.com/in/shouldgo"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'блог'
      url: '/blog/'
    - title: 'обо мне'
      url: '/about/'
    - title: 'контакты'
      url: '/contact/'


#-------------------------------
# Contact Settings
contact:
  email: shouldgo@me.com # Add your form_id
  description: Mria comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Mria theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id